# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SEP6movies

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://sep6movies.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b6908dd078dc462ea0c27d89a95948c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8cc29c4e5a1544fabc6ef987f981e918 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sep6movies.azurecr.io/sep6movies/hello:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sep6movies'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_07f3c59fe1d44373a4421144e621182d }}
        images: 'sep6movies.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b6908dd078dc462ea0c27d89a95948c8 }}/hello:${{ github.sha }}'
